export const countries = [
  // Américas
  { name: 'Brasil', ddi: '55', flag: '🇧🇷', code: 'BR' },
  { name: 'Argentina', ddi: '54', flag: '🇦🇷', code: 'AR' },
  { name: 'Chile', ddi: '56', flag: '🇨🇱', code: 'CL' },
  { name: 'Colômbia', ddi: '57', flag: '🇨🇴', code: 'CO' },
  { name: 'Peru', ddi: '51', flag: '🇵🇪', code: 'PE' },
  { name: 'Equador', ddi: '593', flag: '🇪🇨', code: 'EC' },
  { name: 'Uruguai', ddi: '598', flag: '🇺🇾', code: 'UY' },
  { name: 'Paraguai', ddi: '595', flag: '🇵🇾', code: 'PY' },
  { name: 'Bolívia', ddi: '591', flag: '🇧🇴', code: 'BO' },
  { name: 'Venezuela', ddi: '58', flag: '🇻🇪', code: 'VE' },
  { name: 'México', ddi: '52', flag: '🇲🇽', code: 'MX' },
  { name: 'Estados Unidos', ddi: '1', flag: '🇺🇸', code: 'US' },
  { name: 'Canadá', ddi: '1', flag: '🇨🇦', code: 'CA' },
  { name: 'Costa Rica', ddi: '506', flag: '🇨🇷', code: 'CR' },
  { name: 'Panamá', ddi: '507', flag: '🇵🇦', code: 'PA' },
  { name: 'Guatemala', ddi: '502', flag: '🇬🇹', code: 'GT' },
  { name: 'Honduras', ddi: '504', flag: '🇭🇳', code: 'HN' },
  { name: 'El Salvador', ddi: '503', flag: '🇸🇻', code: 'SV' },
  { name: 'Nicarágua', ddi: '505', flag: '🇳🇮', code: 'NI' },
  { name: 'República Dominicana', ddi: '1', flag: '🇩🇴', code: 'DO' },
  { name: 'Cuba', ddi: '53', flag: '🇨🇺', code: 'CU' },
  { name: 'Jamaica', ddi: '1', flag: '🇯🇲', code: 'JM' },
  { name: 'Porto Rico', ddi: '1', flag: '🇵🇷', code: 'PR' },
  
  // Europa
  { name: 'Portugal', ddi: '351', flag: '🇵🇹', code: 'PT' },
  { name: 'Espanha', ddi: '34', flag: '🇪🇸', code: 'ES' },
  { name: 'França', ddi: '33', flag: '🇫🇷', code: 'FR' },
  { name: 'Alemanha', ddi: '49', flag: '🇩🇪', code: 'DE' },
  { name: 'Itália', ddi: '39', flag: '🇮🇹', code: 'IT' },
  { name: 'Reino Unido', ddi: '44', flag: '🇬🇧', code: 'GB' },
  { name: 'Irlanda', ddi: '353', flag: '🇮🇪', code: 'IE' },
  { name: 'Holanda', ddi: '31', flag: '🇳🇱', code: 'NL' },
  { name: 'Bélgica', ddi: '32', flag: '🇧🇪', code: 'BE' },
  { name: 'Suíça', ddi: '41', flag: '🇨🇭', code: 'CH' },
  { name: 'Áustria', ddi: '43', flag: '🇦🇹', code: 'AT' },
  { name: 'Polônia', ddi: '48', flag: '🇵🇱', code: 'PL' },
  { name: 'Suécia', ddi: '46', flag: '🇸🇪', code: 'SE' },
  { name: 'Noruega', ddi: '47', flag: '🇳🇴', code: 'NO' },
  { name: 'Dinamarca', ddi: '45', flag: '🇩🇰', code: 'DK' },
  { name: 'Finlândia', ddi: '358', flag: '🇫🇮', code: 'FI' },
  { name: 'Grécia', ddi: '30', flag: '🇬🇷', code: 'GR' },
  { name: 'Turquia', ddi: '90', flag: '🇹🇷', code: 'TR' },
  { name: 'Rússia', ddi: '7', flag: '🇷🇺', code: 'RU' },
  
  // Ásia
  { name: 'China', ddi: '86', flag: '🇨🇳', code: 'CN' },
  { name: 'Japão', ddi: '81', flag: '🇯🇵', code: 'JP' },
  { name: 'Índia', ddi: '91', flag: '🇮🇳', code: 'IN' },
  { name: 'Coreia do Sul', ddi: '82', flag: '🇰🇷', code: 'KR' },
  { name: 'Tailândia', ddi: '66', flag: '🇹🇭', code: 'TH' },
  { name: 'Vietnã', ddi: '84', flag: '🇻🇳', code: 'VN' },
  { name: 'Filipinas', ddi: '63', flag: '🇵🇭', code: 'PH' },
  { name: 'Indonésia', ddi: '62', flag: '🇮🇩', code: 'ID' },
  { name: 'Malásia', ddi: '60', flag: '🇲🇾', code: 'MY' },
  { name: 'Singapura', ddi: '65', flag: '🇸🇬', code: 'SG' },
  { name: 'Paquistão', ddi: '92', flag: '🇵🇰', code: 'PK' },
  { name: 'Bangladesh', ddi: '880', flag: '🇧🇩', code: 'BD' },
  { name: 'Arábia Saudita', ddi: '966', flag: '🇸🇦', code: 'SA' },
  { name: 'Emirados Árabes', ddi: '971', flag: '🇦🇪', code: 'AE' },
  { name: 'Israel', ddi: '972', flag: '🇮🇱', code: 'IL' },
  { name: 'Líbano', ddi: '961', flag: '🇱🇧', code: 'LB' },
  { name: 'Irã', ddi: '98', flag: '🇮🇷', code: 'IR' },
  { name: 'Iraque', ddi: '964', flag: '🇮🇶', code: 'IQ' },
  
  // África
  { name: 'África do Sul', ddi: '27', flag: '🇿🇦', code: 'ZA' },
  { name: 'Egito', ddi: '20', flag: '🇪🇬', code: 'EG' },
  { name: 'Nigéria', ddi: '234', flag: '🇳🇬', code: 'NG' },
  { name: 'Quênia', ddi: '254', flag: '🇰🇪', code: 'KE' },
  { name: 'Marrocos', ddi: '212', flag: '🇲🇦', code: 'MA' },
  { name: 'Argélia', ddi: '213', flag: '🇩🇿', code: 'DZ' },
  { name: 'Tunísia', ddi: '216', flag: '🇹🇳', code: 'TN' },
  { name: 'Gana', ddi: '233', flag: '🇬🇭', code: 'GH' },
  { name: 'Angola', ddi: '244', flag: '🇦🇴', code: 'AO' },
  { name: 'Moçambique', ddi: '258', flag: '🇲🇿', code: 'MZ' },
  
  // Oceania
  { name: 'Austrália', ddi: '61', flag: '🇦🇺', code: 'AU' },
  { name: 'Nova Zelândia', ddi: '64', flag: '🇳🇿', code: 'NZ' }
] as const;
