export const countries = [
  // Américas
  { name: 'Brasil', ddi: '55', flag: '🇧🇷' },
  { name: 'Argentina', ddi: '54', flag: '🇦🇷' },
  { name: 'Chile', ddi: '56', flag: '🇨🇱' },
  { name: 'Colômbia', ddi: '57', flag: '🇨🇴' },
  { name: 'Peru', ddi: '51', flag: '🇵🇪' },
  { name: 'Equador', ddi: '593', flag: '🇪🇨' },
  { name: 'Uruguai', ddi: '598', flag: '🇺🇾' },
  { name: 'Paraguai', ddi: '595', flag: '🇵🇾' },
  { name: 'Bolívia', ddi: '591', flag: '🇧🇴' },
  { name: 'Venezuela', ddi: '58', flag: '🇻🇪' },
  { name: 'México', ddi: '52', flag: '🇲🇽' },
  { name: 'Estados Unidos', ddi: '1', flag: '🇺🇸' },
  { name: 'Canadá', ddi: '1', flag: '🇨🇦' },
  { name: 'Costa Rica', ddi: '506', flag: '🇨🇷' },
  { name: 'Panamá', ddi: '507', flag: '🇵🇦' },
  { name: 'Guatemala', ddi: '502', flag: '🇬🇹' },
  { name: 'Honduras', ddi: '504', flag: '🇭🇳' },
  { name: 'El Salvador', ddi: '503', flag: '🇸🇻' },
  { name: 'Nicarágua', ddi: '505', flag: '🇳🇮' },
  { name: 'República Dominicana', ddi: '1', flag: '🇩🇴' },
  { name: 'Cuba', ddi: '53', flag: '🇨🇺' },
  { name: 'Jamaica', ddi: '1', flag: '🇯🇲' },
  { name: 'Porto Rico', ddi: '1', flag: '🇵🇷' },
  
  // Europa
  { name: 'Portugal', ddi: '351', flag: '🇵🇹' },
  { name: 'Espanha', ddi: '34', flag: '🇪🇸' },
  { name: 'França', ddi: '33', flag: '🇫🇷' },
  { name: 'Alemanha', ddi: '49', flag: '🇩🇪' },
  { name: 'Itália', ddi: '39', flag: '🇮🇹' },
  { name: 'Reino Unido', ddi: '44', flag: '🇬🇧' },
  { name: 'Irlanda', ddi: '353', flag: '🇮🇪' },
  { name: 'Holanda', ddi: '31', flag: '🇳🇱' },
  { name: 'Bélgica', ddi: '32', flag: '🇧🇪' },
  { name: 'Suíça', ddi: '41', flag: '🇨🇭' },
  { name: 'Áustria', ddi: '43', flag: '🇦🇹' },
  { name: 'Polônia', ddi: '48', flag: '🇵🇱' },
  { name: 'Suécia', ddi: '46', flag: '🇸🇪' },
  { name: 'Noruega', ddi: '47', flag: '🇳🇴' },
  { name: 'Dinamarca', ddi: '45', flag: '🇩🇰' },
  { name: 'Finlândia', ddi: '358', flag: '🇫🇮' },
  { name: 'Grécia', ddi: '30', flag: '🇬🇷' },
  { name: 'Turquia', ddi: '90', flag: '🇹🇷' },
  { name: 'Rússia', ddi: '7', flag: '🇷🇺' },
  
  // Ásia
  { name: 'China', ddi: '86', flag: '🇨🇳' },
  { name: 'Japão', ddi: '81', flag: '🇯🇵' },
  { name: 'Índia', ddi: '91', flag: '🇮🇳' },
  { name: 'Coreia do Sul', ddi: '82', flag: '🇰🇷' },
  { name: 'Tailândia', ddi: '66', flag: '🇹🇭' },
  { name: 'Vietnã', ddi: '84', flag: '🇻🇳' },
  { name: 'Filipinas', ddi: '63', flag: '🇵🇭' },
  { name: 'Indonésia', ddi: '62', flag: '🇮🇩' },
  { name: 'Malásia', ddi: '60', flag: '🇲🇾' },
  { name: 'Singapura', ddi: '65', flag: '🇸🇬' },
  { name: 'Paquistão', ddi: '92', flag: '🇵🇰' },
  { name: 'Bangladesh', ddi: '880', flag: '🇧🇩' },
  { name: 'Arábia Saudita', ddi: '966', flag: '🇸🇦' },
  { name: 'Emirados Árabes', ddi: '971', flag: '🇦🇪' },
  { name: 'Israel', ddi: '972', flag: '🇮🇱' },
  { name: 'Líbano', ddi: '961', flag: '🇱🇧' },
  { name: 'Irã', ddi: '98', flag: '🇮🇷' },
  { name: 'Iraque', ddi: '964', flag: '🇮🇶' },
  
  // África
  { name: 'África do Sul', ddi: '27', flag: '🇿🇦' },
  { name: 'Egito', ddi: '20', flag: '🇪🇬' },
  { name: 'Nigéria', ddi: '234', flag: '🇳🇬' },
  { name: 'Quênia', ddi: '254', flag: '🇰🇪' },
  { name: 'Marrocos', ddi: '212', flag: '🇲🇦' },
  { name: 'Argélia', ddi: '213', flag: '🇩🇿' },
  { name: 'Tunísia', ddi: '216', flag: '🇹🇳' },
  { name: 'Gana', ddi: '233', flag: '🇬🇭' },
  { name: 'Angola', ddi: '244', flag: '🇦🇴' },
  { name: 'Moçambique', ddi: '258', flag: '🇲🇿' },
  
  // Oceania
  { name: 'Austrália', ddi: '61', flag: '🇦🇺' },
  { name: 'Nova Zelândia', ddi: '64', flag: '🇳🇿' }
] as const;
